#Pipeline for extracting subset of QNAME reads from a bam using a list of QNAMEs from another bam
#Developed for evaluating how mycobacteria contamination affects damage estimates of MTBC mapped reads
#The idea is that you cut damaged bases off the nUDG reads and stringently map them to the MTBC ref (using another pipeline)
#This pipeline makes a list of the QNAMEs in the stringently mapped bam and subsets those reads from a
#loosely mapped bam made from unclipped reads (to preserve damage)
#The resulting bam is therefore your "true" MTBC reads and should, ideally, have the true damage signature
#conda env name QNAMEfilter python=3.8
#conda env list snakemake=5.3.0, picard, samtools, mapdamage2, qualimap
#make list of QNAMES for each stringent bam
#picard filter loose bams using list of QNAMES
#mapdamage filtered bams
#qualimap filtered bams

#list of samples
samples = ["KUE050.A0101.TB", "KUE051.A0101.TB", "KUE052.A0101.TB", "STF001.A0101.TB", "STF001.B0101.TB", "TLT001.A0101.TB", "TLT001.B0101.TB", "TLT001.C0101.TB", "PIA001.A0101.TB", "PIA002.A0101.TB", "SUN001.A0101.TB"]
refseq = ["/data/stonelab/references/MTB_ancestor/MTB_ancestor.fasta"]
nUDGbam = ["/scratch/keblevin/02_12_21_megapipe_MPI_capture2pos_nUDGparams/{sample}/{sample}_f4_q37_sortc_markdup.rescaled.bam"] #
clippedbam = ["/scratch/keblevin/04_01_21_megapipe_MPI_capture2nUDG_trim6/output/{sample}/{sample}_f4_q37_sortc_markdup.rescaled.bam"]
outputdir = ["/scratch/keblevin/041121_damage_comparison/output"]

rule all:
    input:
        "output/SummaryReport.tsv"

rule QNAME:
    input:
         clippedbam
    output:
        "output/QNAMES/{sample}_QNAMES.txt"
    shell:
        "samtools view -h {input} | cut -f1 | sort > {output}"

rule filter:
    input:
        bam = nUDGbam,
        QNAME = "output/QNAMES/{sample}_QNAMES.txt"
    output:
        "output/bams/{sample}_loose_QNAMEfiltered.bam"
    shell:
        "picard FilterSamReads --INPUT {input.bam} --OUTPUT {output} --READ_LIST_FILE {input.QNAME} --FILTER includeReadList"

rule sort:
    input:
        "output/bams/{sample}_loose_QNAMEfiltered.bam"
    output:
        "output/bams/{sample}_loose_QNAMEfiltered_sorted.bam"
    shell:
        "samtools sort -o {output} {input}"

rule index:
    input:
        "output/bams/{sample}_loose_QNAMEfiltered_sorted.bam"
    output:
        "output/bams/{sample}_loose_QNAMEfiltered_sorted.bam.bai"
    shell:
        "samtools index {input}"

rule mapdamage:
    input:
        bam = "output/bams/{sample}_loose_QNAMEfiltered_sorted.bam",
        bai = "output/bams/{sample}_loose_QNAMEfiltered_sorted.bam.bai",
        ref = refseq
    params:
        directory = "output/mapdamage/{sample}_mapDamage"
    output:
        Fivep = "output/mapdamage/{sample}_mapDamage/5pCtoT_freq.txt",
        Threep = "output/mapdamage/{sample}_mapDamage/3pGtoA_freq.txt"
    shell:
         "mapDamage -i {input.bam} -r {input.ref} -d {params.directory}"

rule qualimap:
    input:
        bam = "output/bams/{sample}_loose_QNAMEfiltered_sorted.bam",
        Fivep = "output/mapdamage/{sample}_mapDamage/5pCtoT_freq.txt",
        Threep = "output/mapdamage/{sample}_mapDamage/3pGtoA_freq.txt"
    params:
        outputdir = "output/qualimap/{sample}"
    output:
        "output/qualimap/{sample}/genome_results.txt"
    shell:
        "qualimap bamqc -bam {input.bam} -outdir {params.outputdir}"

rule summaryreports:
    input:
        bam = "output/bams/{sample}_loose_QNAMEfiltered_sorted.bam",
        qualimap = "output/qualimap/{sample}/genome_results.txt",
        Fivep = "output/mapdamage/{sample}_mapDamage/5pCtoT_freq.txt",
        Threep = "output/mapdamage/{sample}_mapDamage/3pGtoA_freq.txt"
    output:
        "output/reports/{sample}_report.txt"
    shell:
        "echo 'Sample Name' >> {output};\
echo {wildcards.sample} >> {output};\
echo 'Q37 dedup QNAME reads' >> {output};\
Q37dedupmapped=$(samtools view -c {input.bam});\
echo $Q37dedupmapped >> {output};\
echo 'Avg length of mapped reads' >> {output};\
avg_length=$(samtools view {input.bam} | awk '{{SUM+=length($10);DIV++}}END{{print SUM/DIV}}');\
echo $avg_length >> {output};\
echo 'Mean Coverage' >> {output};\
mean_cov=$(grep 'mean coverageData' {input.qualimap} | cut -d '=' -f2);\
echo $mean_cov >> {output};\
echo 'Std dev of coverage' >> {output};\
sd_cov=$(grep 'std coverageData' {input.qualimap} | cut -d '=' -f2);\
echo $sd_cov >> {output};\
echo '%ref covered at >=1x' >> {output};\
cov1=$(grep 'reference with a coverageData >= 1X' {input.qualimap} | awk '{{print $4}}');\
echo $cov1 >> {output};\
echo '%ref covered at >=5x' >> {output};\
cov5=$(grep 'reference with a coverageData >= 5X' {input.qualimap} | awk '{{print $4}}');\
echo $cov5 >> {output};\
echo '5pCtoTFirstbp' >> {output};\
cat {input.Fivep} | sed -n '2 p' | awk '{{print $2}}' >> {output};\
echo '5pCtoTSecondbp' >> {output};\
cat {input.Fivep} | sed -n '3 p' | awk '{{print $2}}' >> {output};\
echo '3pGtoAFirstbp' >> {output};\
cat {input.Threep} | sed -n '2 p' | awk '{{print $2}}' >> {output};\
echo '3pGtoASecondpb' >> {output};\
cat {input.Threep} | sed -n '3 p' | awk '{{print $2}}' >> {output};"

rule summarycombined:
    input:
        expand("output/reports/{sample}_report.txt", sample = samples)
    output:
        tsv = "output/SummaryReport.tsv"
    run:
        out = open(output[0], "w")
        out.write("Sample Name\tQ37 dedup QNAME reads\tAvg length of mapped Q37 reads\tMean Cov\tSD Cov\t%ref covered at >=1x\t%ref covered at >=5x\t5pCtoTFirstbp\t5pCtoTSecondbp\t3pGtoAFirstbp\t3pGtoASecondpb\n")

        for file in input:
            f = open(file, "r")
            lines = f.readlines()
            lines =[item.strip() for item in lines]

            sampleInfo = []

            sampleInfo.append(lines[lines.index("Sample Name") + 1 ])
            sampleInfo.append(lines[lines.index("Q37 dedup QNAME reads") + 1 ])
            sampleInfo.append(lines[lines.index("Avg length of mapped reads") + 1 ])
            sampleInfo.append(lines[lines.index("Mean Coverage") + 1 ])
            sampleInfo.append(lines[lines.index("Std dev of coverage") + 1 ])
            sampleInfo.append(lines[lines.index("%ref covered at >=1x") + 1 ])
            sampleInfo.append(lines[lines.index("%ref covered at >=5x") + 1 ])
            sampleInfo.append(lines[lines.index("5pCtoTFirstbp") + 1 ])
            sampleInfo.append(lines[lines.index("5pCtoTSecondbp") + 1 ])
            sampleInfo.append(lines[lines.index("3pGtoAFirstbp") + 1 ])
            sampleInfo.append(lines[lines.index("3pGtoASecondpb") + 1 ])


            writeLine = '\t'.join(sampleInfo)
            writeLine += '\n'
            out.write(writeLine)
            f.close()

        out.close()




